services:
  backupcontroller:
    image: backupcontroller:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: easypanel-backup-agent
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app